version: '3.8'

services:

  moviesapi:
    build: .
    container_name: moviesapi

    ports:
      - "8080:8080"

    volumes:
      - ./wwwroot/uploads:/app/wwwroot/uploads
      - ./movies.db:/app/movies.db

    restart: always

  jenkins:
    build:
      context: ./jenkins

    container_name: jenkins

    user: root

    ports:
      - "8081:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

volumes:
  jenkins_home: